//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodexo_JTH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sodexo_JTH.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission Date:.
        /// </summary>
        public static string adateText {
            get {
                return ResourceManager.GetString("adateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult/Child:.
        /// </summary>
        public static string adchText {
            get {
                return ResourceManager.GetString("adchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        public static string aeText {
            get {
                return ResourceManager.GetString("aeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies:.
        /// </summary>
        public static string algeText {
            get {
                return ResourceManager.GetString("algeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy.
        /// </summary>
        public static string allgeyText {
            get {
                return ResourceManager.GetString("allgeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to menu.
        /// </summary>
        public static string am {
            get {
                return ResourceManager.GetString("am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to menu.
        /// </summary>
        public static string ameContent {
            get {
                return ResourceManager.GetString("ameContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult/Child:.
        /// </summary>
        public static string anmText {
            get {
                return ResourceManager.GetString("anmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed Class:.
        /// </summary>
        public static string bclassText {
            get {
                return ResourceManager.GetString("bclassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed Class:.
        /// </summary>
        public static string bclsText {
            get {
                return ResourceManager.GetString("bclsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        public static string bdText {
            get {
                return ResourceManager.GetString("bdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beverages.
        /// </summary>
        public static string bevText {
            get {
                return ResourceManager.GetString("bevText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast Late Cut off time exceeds.
        /// </summary>
        public static string bf {
            get {
                return ResourceManager.GetString("bf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast Cut off time exceeds.
        /// </summary>
        public static string bfc {
            get {
                return ResourceManager.GetString("bfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast Cut off time: .
        /// </summary>
        public static string bfco {
            get {
                return ResourceManager.GetString("bfco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string bfeText {
            get {
                return ResourceManager.GetString("bfeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast meal Order is already placed..
        /// </summary>
        public static string bfpl {
            get {
                return ResourceManager.GetString("bfpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        public static string btnloginContent {
            get {
                return ResourceManager.GetString("btnloginContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnsearch1Content {
            get {
                return ResourceManager.GetString("btnsearch1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string btnupdateContent {
            get {
                return ResourceManager.GetString("btnupdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string can {
            get {
                return ResourceManager.GetString("can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel this order?.
        /// </summary>
        public static string canc {
            get {
                return ResourceManager.GetString("canc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Id:.
        /// </summary>
        public static string caseText {
            get {
                return ResourceManager.GetString("caseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cut off time exceeds.
        /// </summary>
        public static string cex {
            get {
                return ResourceManager.GetString("cex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Giver.
        /// </summary>
        public static string cgContent {
            get {
                return ResourceManager.GetString("cgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check username you have entered.
        /// </summary>
        public static string chckuser {
            get {
                return ResourceManager.GetString("chckuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any items from Soup,Beverages,Fruit menu and select Meal Option..
        /// </summary>
        public static string clearfeedmsg {
            get {
                return ResourceManager.GetString("clearfeedmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string closeContent {
            get {
                return ResourceManager.GetString("closeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select bed no..
        /// </summary>
        public static string cmbsearchbypatientPlaceholderText {
            get {
                return ResourceManager.GetString("cmbsearchbypatientPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ward  no..
        /// </summary>
        public static string cmbsearchbywardPlaceholderText {
            get {
                return ResourceManager.GetString("cmbsearchbywardPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cnContent {
            get {
                return ResourceManager.GetString("cnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confinement.
        /// </summary>
        public static string cnfContent {
            get {
                return ResourceManager.GetString("cnfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string cnfeContent {
            get {
                return ResourceManager.GetString("cnfeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Order.
        /// </summary>
        public static string codText {
            get {
                return ResourceManager.GetString("codText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed to sync?.
        /// </summary>
        public static string contentdesc {
            get {
                return ResourceManager.GetString("contentdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string contentno {
            get {
                return ResourceManager.GetString("contentno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are  .
        /// </summary>
        public static string contenttit {
            get {
                return ResourceManager.GetString("contenttit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Meal Orders available for sync.
        /// </summary>
        public static string contenttit2 {
            get {
                return ResourceManager.GetString("contenttit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string contentyes {
            get {
                return ResourceManager.GetString("contentyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cor1Text {
            get {
                return ResourceManager.GetString("cor1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string cor2Text {
            get {
                return ResourceManager.GetString("cor2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cut off time: .
        /// </summary>
        public static string cot {
            get {
                return ResourceManager.GetString("cot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Server.
        /// </summary>
        public static string cservText {
            get {
                return ResourceManager.GetString("cservText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUISINE TYPE.
        /// </summary>
        public static string ctText {
            get {
                return ResourceManager.GetString("ctText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portion Size:.
        /// </summary>
        public static string datText {
            get {
                return ResourceManager.GetString("datText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge Date:.
        /// </summary>
        public static string ddateText {
            get {
                return ResourceManager.GetString("ddateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Meal order status changed as delivered.
        /// </summary>
        public static string delivered_message {
            get {
                return ResourceManager.GetString("delivered_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dessert.
        /// </summary>
        public static string dessText {
            get {
                return ResourceManager.GetString("dessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIET TEXTURE.
        /// </summary>
        public static string dietText {
            get {
                return ResourceManager.GetString("dietText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner Late Cut off time exceeds.
        /// </summary>
        public static string dn {
            get {
                return ResourceManager.GetString("dn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner Cut off time exceeds.
        /// </summary>
        public static string dnc {
            get {
                return ResourceManager.GetString("dnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner Cut off time: .
        /// </summary>
        public static string dnco {
            get {
                return ResourceManager.GetString("dnco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string dneText {
            get {
                return ResourceManager.GetString("dneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner meal Order is already placed..
        /// </summary>
        public static string dnpl {
            get {
                return ResourceManager.GetString("dnpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB:.
        /// </summary>
        public static string dobtxtText {
            get {
                return ResourceManager.GetString("dobtxtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Comments:.
        /// </summary>
        public static string doccmnText {
            get {
                return ResourceManager.GetString("doccmnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Order Detail.
        /// </summary>
        public static string dodText {
            get {
                return ResourceManager.GetString("dodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Service:.
        /// </summary>
        public static string dosText {
            get {
                return ResourceManager.GetString("dosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string dteText {
            get {
                return ResourceManager.GetString("dteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposable Tray:.
        /// </summary>
        public static string DTText {
            get {
                return ResourceManager.GetString("DTText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter server ip address.
        /// </summary>
        public static string ent {
            get {
                return ResourceManager.GetString("ent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save server ip address/name..
        /// </summary>
        public static string ent2 {
            get {
                return ResourceManager.GetString("ent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée.
        /// </summary>
        public static string entreeText {
            get {
                return ResourceManager.GetString("entreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD ALLERGIES.
        /// </summary>
        public static string faText {
            get {
                return ResourceManager.GetString("faText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string feedText {
            get {
                return ResourceManager.GetString("feedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback link not available.
        /// </summary>
        public static string flna {
            get {
                return ResourceManager.GetString("flna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid Consistency:.
        /// </summary>
        public static string fluidText {
            get {
                return ResourceManager.GetString("fluidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You changed the patient&apos;s settings. Do you want to delete the future orders of this patient?.
        /// </summary>
        public static string fomsg {
            get {
                return ResourceManager.GetString("fomsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string FrageNr {
            get {
                return ResourceManager.GetString("FrageNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gen Comment:.
        /// </summary>
        public static string gcmnText {
            get {
                return ResourceManager.GetString("gcmnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string genderText {
            get {
                return ResourceManager.GetString("genderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halal/Non-Halal:.
        /// </summary>
        public static string hlnlText {
            get {
                return ResourceManager.GetString("hlnlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halal:.
        /// </summary>
        public static string hlText {
            get {
                return ResourceManager.GetString("hlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGREDIENTS (Excludes).
        /// </summary>
        public static string ieText {
            get {
                return ResourceManager.GetString("ieText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  If you change your meal time, all selected menu items will be deleted. Do you want to change meal time?.
        /// </summary>
        public static string ifu {
            get {
                return ResourceManager.GetString("ifu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juice.
        /// </summary>
        public static string juiceText {
            get {
                return ResourceManager.GetString("juiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Order is Placed Successfully , Kindly contact controller to Approve/Reject the order. \nDo you want to place another order for same patient?.
        /// </summary>
        public static string lateorder {
            get {
                return ResourceManager.GetString("lateorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Late Cut off time exceeds.
        /// </summary>
        public static string le {
            get {
                return ResourceManager.GetString("le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch Late Cut off time exceeds.
        /// </summary>
        public static string lh {
            get {
                return ResourceManager.GetString("lh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch Cut off time exceeds.
        /// </summary>
        public static string lhc {
            get {
                return ResourceManager.GetString("lhc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch Cut off time: .
        /// </summary>
        public static string lhco {
            get {
                return ResourceManager.GetString("lhco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string lheText {
            get {
                return ResourceManager.GetString("lheText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch meal Order is already placed..
        /// </summary>
        public static string lhpl {
            get {
                return ResourceManager.GetString("lhpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string logsure {
            get {
                return ResourceManager.GetString("logsure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not place meal order as meal class name is not active..
        /// </summary>
        public static string mc22 {
            get {
                return ResourceManager.GetString("mc22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Class:.
        /// </summary>
        public static string mcText {
            get {
                return ResourceManager.GetString("mcText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Prefrence Changed!.
        /// </summary>
        public static string ml {
            get {
                return ResourceManager.GetString("ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Order Successfully Cancelled.
        /// </summary>
        public static string ml1 {
            get {
                return ResourceManager.GetString("ml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Order cancellation failed.
        /// </summary>
        public static string ml12 {
            get {
                return ResourceManager.GetString("ml12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Change the (Veg/Nonveg)/(Halal/Non-Halal)/(Allergy) Status..
        /// </summary>
        public static string ml2 {
            get {
                return ResourceManager.GetString("ml2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal confirmation!.
        /// </summary>
        public static string mlc {
            get {
                return ResourceManager.GetString("mlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to confirm order?.
        /// </summary>
        public static string mlc2 {
            get {
                return ResourceManager.GetString("mlc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal order cancellation!.
        /// </summary>
        public static string mo {
            get {
                return ResourceManager.GetString("mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Option:.
        /// </summary>
        public static string mosText {
            get {
                return ResourceManager.GetString("mosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode of transaction:.
        /// </summary>
        public static string motText {
            get {
                return ResourceManager.GetString("motText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal order is already placed..
        /// </summary>
        public static string mp {
            get {
                return ResourceManager.GetString("mp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master data synced successfully..
        /// </summary>
        public static string msg0 {
            get {
                return ResourceManager.GetString("msg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Orders Have been synced successfully.
        /// </summary>
        public static string msg1 {
            get {
                return ResourceManager.GetString("msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not accessible, please check internet connection..
        /// </summary>
        public static string msg10 {
            get {
                return ResourceManager.GetString("msg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available for sync.
        /// </summary>
        public static string msg11 {
            get {
                return ResourceManager.GetString("msg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History cannot be shown in offline mode..
        /// </summary>
        public static string msg12 {
            get {
                return ResourceManager.GetString("msg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Meal order status updated.
        /// </summary>
        public static string msg13 {
            get {
                return ResourceManager.GetString("msg13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to log-out from the application?.
        /// </summary>
        public static string msg2 {
            get {
                return ResourceManager.GetString("msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only FSA and Nurse can login in tablet..
        /// </summary>
        public static string msg22 {
            get {
                return ResourceManager.GetString("msg22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        public static string msg2w {
            get {
                return ResourceManager.GetString("msg2w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter server ip address.
        /// </summary>
        public static string msg3 {
            get {
                return ResourceManager.GetString("msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sync &apos;Sync Masters&apos; and &apos;Sync Menu Items&apos; from drawer menu to proceed further..
        /// </summary>
        public static string msg4 {
            get {
                return ResourceManager.GetString("msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can order meal for two days only..
        /// </summary>
        public static string msg5 {
            get {
                return ResourceManager.GetString("msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORRY, You Are Not Authorised To Take First Order Of Patient.
        /// </summary>
        public static string msg6 {
            get {
                return ResourceManager.GetString("msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient data synced successfully..
        /// </summary>
        public static string msg7 {
            get {
                return ResourceManager.GetString("msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Items synced succeesfully..
        /// </summary>
        public static string msg8 {
            get {
                return ResourceManager.GetString("msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change patient settings during offline mode. Please undo the changes and try again.
        /// </summary>
        public static string msg9 {
            get {
                return ResourceManager.GetString("msg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select patient name from suggestions first.
        /// </summary>
        public static string mss1 {
            get {
                return ResourceManager.GetString("mss1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Summary.
        /// </summary>
        public static string msText {
            get {
                return ResourceManager.GetString("msText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Time.
        /// </summary>
        public static string mteText {
            get {
                return ResourceManager.GetString("mteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Type:.
        /// </summary>
        public static string mtText {
            get {
                return ResourceManager.GetString("mtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item Available .
        /// </summary>
        public static string nit2 {
            get {
                return ResourceManager.GetString("nit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item Available .
        /// </summary>
        public static string nitText {
            get {
                return ResourceManager.GetString("nitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string nmText {
            get {
                return ResourceManager.GetString("nmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no meal history for this patient..
        /// </summary>
        public static string nomealhistrory {
            get {
                return ResourceManager.GetString("nomealhistrory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRIC/ID:.
        /// </summary>
        public static string nricText {
            get {
                return ResourceManager.GetString("nricText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string nxContent {
            get {
                return ResourceManager.GetString("nxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string obyText {
            get {
                return ResourceManager.GetString("obyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string odateText {
            get {
                return ResourceManager.GetString("odateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date:.
        /// </summary>
        public static string odtText {
            get {
                return ResourceManager.GetString("odtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is already Placed in offline mode for this Patient.
        /// </summary>
        public static string offl {
            get {
                return ResourceManager.GetString("offl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sync it from patient details screen..
        /// </summary>
        public static string offl2 {
            get {
                return ResourceManager.GetString("offl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Meal order is already placed..
        /// </summary>
        public static string order_placed {
            get {
                return ResourceManager.GetString("order_placed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Order Status.
        /// </summary>
        public static string orderstatusText {
            get {
                return ResourceManager.GetString("orderstatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHERS.
        /// </summary>
        public static string oteText {
            get {
                return ResourceManager.GetString("oteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others .
        /// </summary>
        public static string otText {
            get {
                return ResourceManager.GetString("otText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Age:.
        /// </summary>
        public static string pageText {
            get {
                return ResourceManager.GetString("pageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Race:.
        /// </summary>
        public static string paraceText {
            get {
                return ResourceManager.GetString("paraceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string patient {
            get {
                return ResourceManager.GetString("patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Masters.
        /// </summary>
        public static string pdataText {
            get {
                return ResourceManager.GetString("pdataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Details.
        /// </summary>
        public static string pdText {
            get {
                return ResourceManager.GetString("pdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Information.
        /// </summary>
        public static string pinameText {
            get {
                return ResourceManager.GetString("pinameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Patient Information.
        /// </summary>
        public static string pio {
            get {
                return ResourceManager.GetString("pio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any items from Entree menu Or select meal option..
        /// </summary>
        public static string pls {
            get {
                return ResourceManager.GetString("pls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select ward number first..
        /// </summary>
        public static string pls11 {
            get {
                return ResourceManager.GetString("pls11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user name and password..
        /// </summary>
        public static string plss {
            get {
                return ResourceManager.GetString("plss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Menu Items.
        /// </summary>
        public static string pmenuText {
            get {
                return ResourceManager.GetString("pmenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Meal Information.
        /// </summary>
        public static string pmname1 {
            get {
                return ResourceManager.GetString("pmname1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Meal Information.
        /// </summary>
        public static string pmnameText {
            get {
                return ResourceManager.GetString("pmnameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string pnameText {
            get {
                return ResourceManager.GetString("pnameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient/NRIC.
        /// </summary>
        public static string pneText {
            get {
                return ResourceManager.GetString("pneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name:.
        /// </summary>
        public static string pnText {
            get {
                return ResourceManager.GetString("pnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        public static string poContent {
            get {
                return ResourceManager.GetString("poContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Order Detail.
        /// </summary>
        public static string porderdText {
            get {
                return ResourceManager.GetString("porderdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Preference: .
        /// </summary>
        public static string pserText {
            get {
                return ResourceManager.GetString("pserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Preference:.
        /// </summary>
        public static string psText {
            get {
                return ResourceManager.GetString("psText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race :.
        /// </summary>
        public static string rcText {
            get {
                return ResourceManager.GetString("rcText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion:.
        /// </summary>
        public static string relText {
            get {
                return ResourceManager.GetString("relText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string remarkText {
            get {
                return ResourceManager.GetString("remarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string rm {
            get {
                return ResourceManager.GetString("rm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter remark.
        /// </summary>
        public static string rm1 {
            get {
                return ResourceManager.GetString("rm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks:.
        /// </summary>
        public static string rmsText {
            get {
                return ResourceManager.GetString("rmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string sall {
            get {
                return ResourceManager.GetString("sall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Patient Name.
        /// </summary>
        public static string sbpText {
            get {
                return ResourceManager.GetString("sbpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By ward No..
        /// </summary>
        public static string sbwText {
            get {
                return ResourceManager.GetString("sbwText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned order id does not match.
        /// </summary>
        public static string scanned_orderid_not_match {
            get {
                return ResourceManager.GetString("scanned_orderid_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync done successfully..
        /// </summary>
        public static string sd {
            get {
                return ResourceManager.GetString("sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Patient.
        /// </summary>
        public static string searchPat {
            get {
                return ResourceManager.GetString("searchPat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Bed &amp; MealTime to continue...
        /// </summary>
        public static string selbedmeal {
            get {
                return ResourceManager.GetString("selbedmeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Ward and mealtime first..
        /// </summary>
        public static string select_ward_mealtime_first {
            get {
                return ResourceManager.GetString("select_ward_mealtime_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the server failed, please check.
        /// </summary>
        public static string serv {
            get {
                return ResourceManager.GetString("serv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please login again..
        /// </summary>
        public static string session {
            get {
                return ResourceManager.GetString("session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string slText {
            get {
                return ResourceManager.GetString("slText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Patient Data.
        /// </summary>
        public static string spdataText {
            get {
                return ResourceManager.GetString("spdataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soup.
        /// </summary>
        public static string spText {
            get {
                return ResourceManager.GetString("spText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr. No..
        /// </summary>
        public static string srnText {
            get {
                return ResourceManager.GetString("srnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string srText {
            get {
                return ResourceManager.GetString("srText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string statusText {
            get {
                return ResourceManager.GetString("statusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string sv {
            get {
                return ResourceManager.GetString("sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing....
        /// </summary>
        public static string sync {
            get {
                return ResourceManager.GetString("sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sync &apos;Sync Menu Items&apos; from drawer menu to proceed further..
        /// </summary>
        public static string syncmenuitem {
            get {
                return ResourceManager.GetString("syncmenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no offline order to be sync..
        /// </summary>
        public static string syncofforder {
            get {
                return ResourceManager.GetString("syncofforder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Offline Order.
        /// </summary>
        public static string syncoffText {
            get {
                return ResourceManager.GetString("syncoffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string tblkgenderText {
            get {
                return ResourceManager.GetString("tblkgenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H-NH.
        /// </summary>
        public static string tblkH_NHText {
            get {
                return ResourceManager.GetString("tblkH_NHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Order Taken By.
        /// </summary>
        public static string tblklastmodifiedText {
            get {
                return ResourceManager.GetString("tblklastmodifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string tblkorderText {
            get {
                return ResourceManager.GetString("tblkorderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string tblkRText {
            get {
                return ResourceManager.GetString("tblkRText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Type / Therapeutic:.
        /// </summary>
        public static string therText {
            get {
                return ResourceManager.GetString("therText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIET TYPE / THERAPEUTIC.
        /// </summary>
        public static string thText {
            get {
                return ResourceManager.GetString("thText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRIC:.
        /// </summary>
        public static string tidText {
            get {
                return ResourceManager.GetString("tidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string txtamtText {
            get {
                return ResourceManager.GetString("txtamtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string txtAppVersion {
            get {
                return ResourceManager.GetString("txtAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string txtAutoSuggestBoxPlaceholderText {
            get {
                return ResourceManager.GetString("txtAutoSuggestBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed:.
        /// </summary>
        public static string txtbedText {
            get {
                return ResourceManager.GetString("txtbedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Details.
        /// </summary>
        public static string txtblockpatientsearchText {
            get {
                return ResourceManager.GetString("txtblockpatientsearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string txtCatText {
            get {
                return ResourceManager.GetString("txtCatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Type / Therapeutic.
        /// </summary>
        public static string txtdat {
            get {
                return ResourceManager.GetString("txtdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string txtDataText {
            get {
                return ResourceManager.GetString("txtDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:  .
        /// </summary>
        public static string txtDateText {
            get {
                return ResourceManager.GetString("txtDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetic.
        /// </summary>
        public static string txtdiaContent {
            get {
                return ResourceManager.GetString("txtdiaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string txtlogin {
            get {
                return ResourceManager.GetString("txtlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string txtloginText {
            get {
                return ResourceManager.GetString("txtloginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string txtlogText {
            get {
                return ResourceManager.GetString("txtlogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string txtmiText {
            get {
                return ResourceManager.GetString("txtmiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id:.
        /// </summary>
        public static string txtoidText {
            get {
                return ResourceManager.GetString("txtoidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string txtok {
            get {
                return ResourceManager.GetString("txtok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string txtpassPlaceholderText {
            get {
                return ResourceManager.GetString("txtpassPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Search.
        /// </summary>
        public static string txtPatientSearch {
            get {
                return ResourceManager.GetString("txtPatientSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync All Master Data.
        /// </summary>
        public static string txtSyncMaster {
            get {
                return ResourceManager.GetString("txtSyncMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Menu Master.
        /// </summary>
        public static string txtSyncMenu {
            get {
                return ResourceManager.GetString("txtSyncMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total : .
        /// </summary>
        public static string txttotText {
            get {
                return ResourceManager.GetString("txttotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string txtusernamePlaceholderText {
            get {
                return ResourceManager.GetString("txtusernamePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward-Bed :.
        /// </summary>
        public static string txtWardbedsText {
            get {
                return ResourceManager.GetString("txtWardbedsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward-Bed.
        /// </summary>
        public static string txtWardbedText {
            get {
                return ResourceManager.GetString("txtWardbedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward:.
        /// </summary>
        public static string txtWardText {
            get {
                return ResourceManager.GetString("txtWardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegeterian:.
        /// </summary>
        public static string vegText {
            get {
                return ResourceManager.GetString("vegText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string verify {
            get {
                return ResourceManager.GetString("verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veg/Non-Veg:.
        /// </summary>
        public static string vnText {
            get {
                return ResourceManager.GetString("vnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we sync all data. &amp;#10;This might take some time....
        /// </summary>
        public static string waitmsg {
            get {
                return ResourceManager.GetString("waitmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward No.-Bed No..
        /// </summary>
        public static string wardbed {
            get {
                return ResourceManager.GetString("wardbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward.
        /// </summary>
        public static string wdText {
            get {
                return ResourceManager.GetString("wdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t select more than one item..
        /// </summary>
        public static string yc {
            get {
                return ResourceManager.GetString("yc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your order is cancelled. Do you want to place order for same patient?.
        /// </summary>
        public static string ycn {
            get {
                return ResourceManager.GetString("ycn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your order is confirmed. Do you want to place another order for same patient?.
        /// </summary>
        public static string yo {
            get {
                return ResourceManager.GetString("yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your order is Saved Locally ,it will be confirmed when Internet is available and syncing from menu bar. Do you want to place order for same patient?.
        /// </summary>
        public static string yoff {
            get {
                return ResourceManager.GetString("yoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is not confirmed, there is some problem to process your request. Please check your internet connection..
        /// </summary>
        public static string yon {
            get {
                return ResourceManager.GetString("yon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is not confirmed, there is some problem to process your request. Please check your internet connection.
        /// </summary>
        public static string yor {
            get {
                return ResourceManager.GetString("yor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have un-selected .
        /// </summary>
        public static string yun {
            get {
                return ResourceManager.GetString("yun", resourceCulture);
            }
        }
    }
}
